import {Theme} from "./types";

export const colors: Theme['colors'] =  {
    primary: 'var(--md-color-primary)',
    onPrimary: 'var(--md-color-on-primary)',
    primaryContainer: 'var(--md-color-primary-container)',
    onPrimaryContainer: 'var(--md-color-on-primary-container)',
    secondary: 'var(--md-color-secondary)',
    onSecondary: 'var(--md-color-on-secondary)',
    secondaryContainer: 'var(--md-color-secondary-container)',
    onSecondaryContainer: 'var(--md-color-on-secondary-container)',
    tertiary: 'var(--md-color-tertiary)',
    onTertiary: 'var(--md-color-on-tertiary)',
    tertiaryContainer: 'var(--md-color-tertiary-container)',
    onTertiaryContainer: 'var(--md-color-on-terti)',
    error: 'var(--md-color-error)',
    onError: 'var(--md-color-on-error)',
    errorContainer: 'var(--md-color-error-container)',
    onErrorContainer: 'var(--md-color-on-error-container)',
    background: 'var(--md-color-background)',
    onBackground: 'var(--md-color-on-background)',
    surface: 'var(--md-color-surface)',
    onSurface: 'var(--md-color-on-surface)',
    surfaceVariant: 'var(--md-color-surface-variant)',
    onSurfaceVariant: 'var(--md-color-on-surface-variant)',
    outline: 'var(--md-color-outline)',
    outlineVariant: 'var(--md-color-outline-variant)',
    shadow: 'var(--md-color-shadow)',
    scrim: 'var(--md-color-scrim)',
    inverseSurface: 'var(--md-color-inverse-surface)',
    inverseOnSurface: 'var(--md-color-inverse-on-surface)',
    inversePrimary: 'var(--md-color-inverse-primary)',
}

