import { Theme } from "./types";

export const colors: Theme['colors'] =  {
    primary: 'rgba(var(--md-color-primary), 1)',
    onPrimary: 'rgba(var(--md-color-on-primary), 1)',
    primaryContainer: 'rgba(var(--md-color-primary-container), 1)',
    onPrimaryContainer: 'rgba(var(--md-color-on-primary-container), 1)',
    secondary: 'rgba(var(--md-color-secondary), 1)',
    onSecondary: 'rgba(var(--md-color-on-secondary), 1)',
    secondaryContainer: 'rgba(var(--md-color-secondary-container), 1)',
    onSecondaryContainer: 'rgba(var(--md-color-on-secondary-container), 1)',
    tertiary: 'rgba(var(--md-color-tertiary), 1)',
    onTertiary: 'rgba(var(--md-color-on-tertiary), 1)',
    tertiaryContainer: 'rgba(var(--md-color-tertiary-container), 1)',
    onTertiaryContainer: 'rgba(var(--md-color-on-terti), 1)',
    error: 'rgba(var(--md-color-error), 1)',
    onError: 'rgba(var(--md-color-on-error), 1)',
    errorContainer: 'rgba(var(--md-color-error-container), 1)',
    onErrorContainer: 'rgba(var(--md-color-on-error-container), 1)',
    background: 'rgba(var(--md-color-background), 1)',
    onBackground: 'rgba(var(--md-color-on-background), 1)',
    surface: 'rgba(var(--md-color-surface), 1)',
    onSurface: 'rgba(var(--md-color-on-surface), 1)',
    surfaceVariant: 'rgba(var(--md-color-surface-variant), 1)',
    onSurfaceVariant: 'rgba(var(--md-color-on-surface-variant), 1)',
    outline: 'rgba(var(--md-color-outline), 1)',
    outlineVariant: 'rgba(var(--md-color-outline-variant), 1)',
    shadow: 'rgba(var(--md-color-shadow), 1)',
    scrim: 'rgba(var(--md-color-scrim), 1)',
    inverseSurface: 'rgba(var(--md-color-inverse-surface), 1)',
    inverseOnSurface: 'rgba(var(--md-color-inverse-on-surface), 1)',
    inversePrimary: 'rgba(var(--md-color-inverse-primary), 1)',
}

